export type GalleryItem = {
  id: string;
  type: "photo" | "video";
  src: string;
  thumbnail: string;
  title: string;
  category: string;
  year: number;
};

export const galleryItems: GalleryItem[] = [
  // -- Photos ------------------------------------------------------------------
  {
    id: "photo-1",
    type: "photo",
    src: "/images/hero-bg.webp",
    thumbnail: "/images/hero-bg.webp",
    title: "Match Day Intensity",
    category: "Match",
    year: 2024,
  },
  {
    id: "photo-2",
    type: "photo",
    src: "/images/hero-bg-2.webp",
    thumbnail: "/images/hero-bg-2.webp",
    title: "Team Training Session",
    category: "Training",
    year: 2024,
  },
  {
    id: "photo-3",
    type: "photo",
    src: "/images/hero-bg-3.webp",
    thumbnail: "/images/hero-bg-3.webp",
    title: "Stadium Atmosphere",
    category: "Fans",
    year: 2024,
  },
  {
    id: "photo-4",
    type: "photo",
    src: "/images/news/grassroots.png",
    thumbnail: "/images/news/grassroots.png",
    title: "Grassroots Development",
    category: "Community",
    year: 2024,
  },
  {
    id: "photo-5",
    type: "photo",
    src: "/images/news/unites.png",
    thumbnail: "/images/news/unites.png",
    title: "Football Unites Everyone",
    category: "Community",
    year: 2024,
  },

  // -- IFC Lekki 8 Aside Tournament 2016 --------------------------------------
  {
    id: "t16-1",
    type: "video",
    src: "https://www.youtube.com/embed/ps3g7FmL0FM",
    thumbnail: "https://img.youtube.com/vi/ps3g7FmL0FM/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 1",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-2",
    type: "video",
    src: "https://www.youtube.com/embed/yngbAVsEE34",
    thumbnail: "https://img.youtube.com/vi/yngbAVsEE34/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 2",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-3",
    type: "video",
    src: "https://www.youtube.com/embed/cU4g4bdaYB8",
    thumbnail: "https://img.youtube.com/vi/cU4g4bdaYB8/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 3",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-4",
    type: "video",
    src: "https://www.youtube.com/embed/SM3N4yrQGG4",
    thumbnail: "https://img.youtube.com/vi/SM3N4yrQGG4/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 4",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-5",
    type: "video",
    src: "https://www.youtube.com/embed/cyls8yP39vg",
    thumbnail: "https://img.youtube.com/vi/cyls8yP39vg/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 5",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-6",
    type: "video",
    src: "https://www.youtube.com/embed/k8XDfaYcjVE",
    thumbnail: "https://img.youtube.com/vi/k8XDfaYcjVE/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 6",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-7",
    type: "video",
    src: "https://www.youtube.com/embed/dN7x8HW4t2Y",
    thumbnail: "https://img.youtube.com/vi/dN7x8HW4t2Y/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 7",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-8",
    type: "video",
    src: "https://www.youtube.com/embed/Bo2wnvej6M0",
    thumbnail: "https://img.youtube.com/vi/Bo2wnvej6M0/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 8",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-9",
    type: "video",
    src: "https://www.youtube.com/embed/tt-WkLo8UfY?start=40",
    thumbnail: "https://img.youtube.com/vi/tt-WkLo8UfY/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 9",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-10",
    type: "video",
    src: "https://www.youtube.com/embed/i-JIMowSXac?start=27",
    thumbnail: "https://img.youtube.com/vi/i-JIMowSXac/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 10",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-11",
    type: "video",
    src: "https://www.youtube.com/embed/_o9RzjtKEfY",
    thumbnail: "https://img.youtube.com/vi/_o9RzjtKEfY/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 11",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-12",
    type: "video",
    src: "https://www.youtube.com/embed/O0xT3PwTBSA?start=31",
    thumbnail: "https://img.youtube.com/vi/O0xT3PwTBSA/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 12",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-13",
    type: "video",
    src: "https://www.youtube.com/embed/DaaOfYGvBOs",
    thumbnail: "https://img.youtube.com/vi/DaaOfYGvBOs/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 13",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-14",
    type: "video",
    src: "https://www.youtube.com/embed/FxOG04BjyE8",
    thumbnail: "https://img.youtube.com/vi/FxOG04BjyE8/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 14",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-15",
    type: "video",
    src: "https://www.youtube.com/embed/uTynuwiOvCY",
    thumbnail: "https://img.youtube.com/vi/uTynuwiOvCY/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 15",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-16",
    type: "video",
    src: "https://www.youtube.com/embed/KtkrbwBOBGQ",
    thumbnail: "https://img.youtube.com/vi/KtkrbwBOBGQ/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 16",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-17",
    type: "video",
    src: "https://www.youtube.com/embed/3hr_NEz-lbA",
    thumbnail: "https://img.youtube.com/vi/3hr_NEz-lbA/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 17",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-18",
    type: "video",
    src: "https://www.youtube.com/embed/ACaOaZfZnIg",
    thumbnail: "https://img.youtube.com/vi/ACaOaZfZnIg/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 18",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-19",
    type: "video",
    src: "https://www.youtube.com/embed/Gqoi83wuhlI",
    thumbnail: "https://img.youtube.com/vi/Gqoi83wuhlI/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 19",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-20",
    type: "video",
    src: "https://www.youtube.com/embed/dhA7Rjf_b7Q",
    thumbnail: "https://img.youtube.com/vi/dhA7Rjf_b7Q/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 20",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-21",
    type: "video",
    src: "https://www.youtube.com/embed/x-_goobVbps",
    thumbnail: "https://img.youtube.com/vi/x-_goobVbps/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 21",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-22",
    type: "video",
    src: "https://www.youtube.com/embed/3agN6lPNnUA",
    thumbnail: "https://img.youtube.com/vi/3agN6lPNnUA/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 22",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-23",
    type: "video",
    src: "https://www.youtube.com/embed/TE3eZoK6z3w",
    thumbnail: "https://img.youtube.com/vi/TE3eZoK6z3w/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 23",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-24",
    type: "video",
    src: "https://www.youtube.com/embed/8xDS0UlRQGM",
    thumbnail: "https://img.youtube.com/vi/8xDS0UlRQGM/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 24",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-25",
    type: "video",
    src: "https://www.youtube.com/embed/bxBV1R54LCw",
    thumbnail: "https://img.youtube.com/vi/bxBV1R54LCw/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 25",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-26",
    type: "video",
    src: "https://www.youtube.com/embed/7ACYbA4S-jI",
    thumbnail: "https://img.youtube.com/vi/7ACYbA4S-jI/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 26",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-27",
    type: "video",
    src: "https://www.youtube.com/embed/uiGuWx_H-Xc",
    thumbnail: "https://img.youtube.com/vi/uiGuWx_H-Xc/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 27",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-28",
    type: "video",
    src: "https://www.youtube.com/embed/WkaF9bJsgHg",
    thumbnail: "https://img.youtube.com/vi/WkaF9bJsgHg/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 28",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-29",
    type: "video",
    src: "https://www.youtube.com/embed/1MZ30mPoVxQ",
    thumbnail: "https://img.youtube.com/vi/1MZ30mPoVxQ/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 29",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-30",
    type: "video",
    src: "https://www.youtube.com/embed/uGp2uzNA7Lc",
    thumbnail: "https://img.youtube.com/vi/uGp2uzNA7Lc/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 30",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-31",
    type: "video",
    src: "https://www.youtube.com/embed/FzSve0xdUZw",
    thumbnail: "https://img.youtube.com/vi/FzSve0xdUZw/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 31",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-32",
    type: "video",
    src: "https://www.youtube.com/embed/dDf89Sdf7F8",
    thumbnail: "https://img.youtube.com/vi/dDf89Sdf7F8/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 32",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-33",
    type: "video",
    src: "https://www.youtube.com/embed/LiRp0-xCxNA",
    thumbnail: "https://img.youtube.com/vi/LiRp0-xCxNA/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 33",
    category: "Tournament 2016",
    year: 2016,
  },
  {
    id: "t16-34",
    type: "video",
    src: "https://www.youtube.com/embed/zwKD-aTtvGY?start=69",
    thumbnail: "https://img.youtube.com/vi/zwKD-aTtvGY/maxresdefault.jpg",
    title: "Ifc Lekki 8 Aside Tournament 2016 - 34",
    category: "Tournament 2016",
    year: 2016,
  },

  // -- IFC Lekki Soccer May 2015 ----------------------------------------------
  {
    id: "s15-1",
    type: "video",
    src: "https://www.youtube.com/embed/ccQoT2I10MU",
    thumbnail: "https://img.youtube.com/vi/ccQoT2I10MU/maxresdefault.jpg",
    title: "IFC Lekki Soccer May 2015 - 1",
    category: "Soccer May 2015",
    year: 2015,
  },
  {
    id: "s15-2",
    type: "video",
    src: "https://www.youtube.com/embed/OkF9QTNI5PU",
    thumbnail: "https://img.youtube.com/vi/OkF9QTNI5PU/maxresdefault.jpg",
    title: "IFC Lekki Soccer May 2015 - 2",
    category: "Soccer May 2015",
    year: 2015,
  },
  {
    id: "s15-3",
    type: "video",
    src: "https://www.youtube.com/embed/dRzZ8fyw8go?start=12",
    thumbnail: "https://img.youtube.com/vi/dRzZ8fyw8go/maxresdefault.jpg",
    title: "IFC Lekki Soccer May 2015 - 3",
    category: "Soccer May 2015",
    year: 2015,
  },
  {
    id: "s15-4",
    type: "video",
    src: "https://www.youtube.com/embed/uVBV73sdafE",
    thumbnail: "https://img.youtube.com/vi/uVBV73sdafE/maxresdefault.jpg",
    title: "IFC Lekki Soccer May 2015 - 4",
    category: "Soccer May 2015",
    year: 2015,
  },
  {
    id: "s15-5",
    type: "video",
    src: "https://www.youtube.com/embed/slphqphysSE",
    thumbnail: "https://img.youtube.com/vi/slphqphysSE/maxresdefault.jpg",
    title: "IFC Lekki Soccer May 2015 - 5",
    category: "Soccer May 2015",
    year: 2015,
  },
  {
    id: "s15-6",
    type: "video",
    src: "https://www.youtube.com/embed/tnw6L5a1mN4",
    thumbnail: "https://img.youtube.com/vi/tnw6L5a1mN4/maxresdefault.jpg",
    title: "IFC Lekki Soccer May 2015 - 6",
    category: "Soccer May 2015",
    year: 2015,
  },
];
